#1. node.js base image
FROM node:22

#2. Set Working Directory
WORKDIR /app

#3. copy package.json and package-lock.json(copy all dependencies)
COPY package*.json .

#4. install dependencies
RUN  npm install 

#5. copy the rest of application code
COPY . .

#6. Expose the port the app runs on
EXPOSE 3001

#7. Start the application
CMD ["node","Server.js"]

